management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      group:
        custom:
          include: '*'
      probes:
        enabled: 'true'
      show-details: ALWAYS
      show-components: ALWAYS
server:
  port: '8090'
spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root12sanc@tweetappdb.botptal.mongodb.net/?retryWrites=true&w=majority
      database: tweetappdb
  profiles:
    active: nonprod
